user:
  role: developer

rabbitmq:
  config:
    queues:
      productList: productListQ
      createProduct: createProductQ

    exchange: productExchange

    routingKeys:
      productList: productListKey
      createProduct: createProductKey
